url: ''
baseurl: ''
title: 'Scott Chacon'

permalink: pretty

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
